NAME    = ft_ls
CC      = cc
CFLAGS  = -Wall -Wextra -Werror
RM      = rm -f

SRC     = main.c parse.c vec.c collect.c sort.c print.c recurse.c
OBJ     = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
